### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by lin-xin** [github1586/vue-bnhcp#2]
```
$ npm run dev

> bnhcp@1.0.0 dev D:\project\test\vue-bnhcp-master
> backpack dev

 ERROR  Failed to compile with 1 errors16:34:56

This relative module was not found:

* ./api in ./server/index.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\project\test\vue-bnhcp-master\build\main.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

```
找不到这个 build/main.js ，可项目中都没这个文件夹啊？

**Comment by liyashuang** [comment]
同问

**Comment by lin-xin** [comment]
而且我看了 server/inde.js 里有 import api from './api' ，同级目录下也没有这个api文件啊，是不是有文件没上传上来？

**Comment by github1586** [comment]
@lin-xin @liyashuang  
cd local/template  去这个里面npm install 然后npm run dev  
这个里面有api文件夹   都是本地写死的数据~

**Comment by lin-xin** [comment]
@github1586 在 local/template 依然报错。。。
```
Error: Cannot find module 'D:\project\test\vue-bnhcp-master\local\template\build\main.js'

```

**Comment by github1586** [comment]
@lin-xin 可以联系我qq 截图 我看看。我这边是可以的。

**Comment by liyashuang** [comment]
![image](https://user-images.githubusercontent.com/24770453/29595057-a302c30c-87e7-11e7-8643-13edfa7420ef.png)

**Comment by github1586** [comment]
@liyashuang 报什么错呢？

**Comment by lin-xin** [comment]
@github1586 你的 .gitignore 文件把 build 文件夹给忽略了，没上传上来，难怪老是找不到里面的 main.js

**Comment by github1586** [comment]
@lin-xin 在更新一下 我修改了下

**Comment by lin-xin** [comment]
根目录下的 .gitignore 好像没改吧？

**Comment by github1586** [comment]
@跟这个没关系 build是自己生成的

**Comment by github1586** [comment]
cd local/template 去这个里面npm install 然后npm run dev

**Comment by lin-xin** [comment]
好，我再试试

**Comment by github1586** [comment]
根目录跑不起来  需要搭建数据库

**Comment by liyashuang** [comment]
![image](https://user-images.githubusercontent.com/24770453/29595749-0c732cf6-87ec-11e7-9b07-8605ceaba99f.png)

**Comment by github1586** [comment]
@liyashuang  把根目录的package.josn 放到template 目录下  重新 npm install 试试~

**Comment by github1586** [comment]
nuxt 版本 换为  v1.0.0-alpha.4

**Comment by github1586** [comment]
每个包版本前面的 ^  去掉
