### ISSUE TITLE
项目启动时报错，找不到./api

### ISSUE THREAD

**Issue by MinWest** [github1586/vue-bnhcp#5]
```
import api from './api'
```

![0bc20cd0-71b3-41e5-8af5-31bfcb7ebb71](https://user-images.githubusercontent.com/11186170/30004929-1e295b74-910a-11e7-85f1-61f87bf836b0.png)

**Comment by github1586** [comment]
@MinWest cd local/template 去这个里面npm install 然后npm run dev
这个里面有api文件夹 都是本地写死的数据~
