### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by iamsee** [github1586/vue-bnhcp#6]
This relative module was not found:

* ./api in ./server/index.js
module.js:487
    throw err;
    ^

Error: Cannot find module 'vue-bnhcp/build/main.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by github1586** [comment]
@iamsee  cd local/template 去这个里面npm install 然后npm run dev
这个里面有api文件夹 都是本地写死的数据~

**Comment by MinWest** [comment]
local/template 目录下没有找到api文件夹，在这个目录下npm install & npm run dev报错如下
Entry module not found: Error: Can't resolve './server/index.js' in '/github/vue-bnhcp/local/template'

**Comment by github1586** [comment]
cd local/template/server  里面是有api的 在template下npm

**Comment by iamsee** [comment]
好的，今晚尝试一下，谢谢
